---
title: "Indicator Metatdata"
output: github_document
---

+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+--------------------------------+-----------------+
| Indicator                               | Dataset used                                                                                                                                                 | Function / file name         | Processing script (if applicable) | Indicator Description                                                                                                                                             | Time frame / last updated | Spatial resolution (if raster) | Phase 2 Updated |
+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+--------------------------------+-----------------+
| Heat index                              | [MODIS daily land surface temperature](https://developers.google.com/earth-engine/datasets/catalog/MODIS_061_MYD11A1#description)                            | python/calc_myd11_lst_day.py | procces_data/process_lst.R        | Mean daily LST for summer months (June-August) from the last 10 years (2012-2022) averaged within prison boundaries.                                              | 2012 - 2022               | 1 km                           |                 |
+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+--------------------------------+-----------------+
| Canopy cover                            | [USGS National Land Cover Database](https://developers.google.com/earth-engine/datasets/catalog/USGS_NLCD_RELEASES_2016_REL)                                 | python/calc_canopy_cover.py  |                                   | Average percent canopy cover within prison boundaries + 1km buffer.                                                                                               | 2016                      | 30 m                           |                 |
+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+--------------------------------+-----------------+
| Wildfire risk                           | [Wildfire Hazard Potential for the United States](https://www.fs.usda.gov/rds/archive/catalog/RDS-2015-0047-4)                                               | calc_wildfire_risk.R         |                                   | Mean wildfire hazard potential within prison boundary + 1km buffer                                                                                                | 2024                      | 270 m                          | Yes             |
+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+--------------------------------+-----------------+
| Flood risk                              | [FEMA National Flood Hazard Layer](https://www.fema.gov/flood-maps/national-flood-hazard-layer)                                                              | calc_flood_risk.R            |                                   | Percentage of each prison boundary + 1km buffer that is covered by a high risk flood zone (Zones A and Z; at least a one percent chance of flooding annually)     | August 2021               |                                |                 |
+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+--------------------------------+-----------------+
| Ozone                                   | [SEDAC Annual O3 Concentrations for CONUS](https://sedac.ciesin.columbia.edu/data/set/aqdh-o3-concentrations-contiguous-us-1-km-2000-2016)                   | calc_ozone.R                 |                                   | Average annual ozone levels for 2015 and 2016 within prison boundaries + 1km buffer                                                                               | 2015-2016                 | 1 km                           |                 |
+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+--------------------------------+-----------------+
| PM 2.5                                  | [SEDAC Annual PM2.5 Concentrations for CONUS](https://sedac.ciesin.columbia.edu/data/set/aqdh-pm2-5-concentrations-contiguous-us-1-km-2000-2016)             | calc_pm25.R                  |                                   | Average annual PM2.5 levels for 2015 and 2016 within prison boundaries + 1km buffer                                                                               | 2015-2016                 | 1 km                           |                 |
+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+--------------------------------+-----------------+
| Traffic volume and proximity            | [FHA's Annual Average Daily Traffic](https://www.fhwa.dot.gov/policyinformation/hpms/shapefiles.cfm)                                                         | calc_traffic_proximity.R     | process_data/process_traffic.R    | Count of vehicles (AADT, avg. annual daily traffic) at major roads within 500 meters, divided by distance in meters                                               | 2018                      |                                |                 |
+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+--------------------------------+-----------------+
| Pesticide use                           | [SEDAC Global Pesticide Grids](https://sedac.ciesin.columbia.edu/data/set/ferman-v1-pest-chemgrids-v1-01)                                                    | calc_pesticides.R            |                                   | The total pesticide application from 2015 in kg/ha\*yr averaged over prison boundaries + 1km buffer.                                                              | 2015                      | \~ 10 km (5 arc-minute)        |                 |
+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+--------------------------------+-----------------+
| Superfund/NPL proximity                 | [EPA](https://cumulis.epa.gov/supercpad/CurSites/srchsites.cfm) (click 'View a list of all NPL and SAA sites' then 'Download Excel file')                    | calc_npl_proximity.R         | process_data/process_npl.R        | Count of proposed and listed NPL facilities within 5km (or nearest one beyond 5km) each divided by the distance in km                                             | February 2026             |                                | Yes             |
+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+--------------------------------+-----------------+
| Risk Management Plan facility proximity | [The Data Liberation Project - EPA Risk Management Program Database](https://www.data-liberation-project.org/datasets/epa-risk-management-program-database/) | calc_rmp_proximity.R         |                                   | Count of Risk Management Plan (potential chemical accident management plan) facilities within 5km (or nearest one beyond 5km) each divided by the distance in km. | january 2026              |                                | Yes             |
|                                         |                                                                                                                                                              |                              |                                   |                                                                                                                                                                   |                           |                                |                 |
|                                         |                                                                                                                                                              |                              |                                   | Modeled after EJ Screen methods (pg. 21): <https://www.epa.gov/sites/default/files/2021-04/documents/ejscreen_technical_document.pdf>                             |                           |                                |                 |
+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+--------------------------------+-----------------+
| Hazardous waste facility proximity      | [EPA FRS geospatial download](https://www.epa.gov/frs/geospatial-data-download-service) (Downloaded the National and State ALL FRS single CSV file)          | calc_haz_waste_proximity.R   | process_data/process_haz_waste/R  | Count of hazardous waste facilities within 5km of prison boundary (or nearest beyond 5km) each divided by distance in km                                          | January 2025              |                                | Yes             |
+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+--------------------------------+-----------------+
